---
phone_books_source_repo: "ssh://git@ec2-18-209-44-23.compute-1.amazonaws.com:2222/lusianne/crud-application-using-flask-and-mysql_ci.git"
phone_books_source_branch: "master"
phone_books_image_tag: "gitlabCICD"
phone_books_dest_repo: "phoneBooks_gitlab_CICD"

gitlab_container_registry_name : "gitlab.samiamoura.com"

home: "/home/centos"
volume_database: "/srv/db-data"

ip_addr_server_gitlab: "18.209.44.23"
dns_addr_server_gitlab: "ec2-18-209-44-23.compute-1.amazonaws.com"
ip_addr_preprod: "3.81.96.186"
ip_addr_prod: "54.166.163.77"
port_app: "8181"

#secret data vaulted
github_private_key: "{{ vault_github_private_key }}"
gitlab_private_key: "{{ vault_gitlab_private_key }}"
certificate_domaine: "{{ vault_cacrt_file }}"


docker_hub_login: "{{ vault_docker_hub_login }}"
docker_hub_email: "{{ vault_docker_hub_email }}"
docker_hub_password: "{{ vault_docker_hub_password }}"

gitlab_container_registry_username: "{{ vault_container_registry_gitlab_username }}"
gitlab_container_registry_password: "{{ vault_container_registry_gitlab_password }}"
